# Generated by Django 2.0.7 on 2018-07-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTargetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thname', models.CharField(max_length=150)),
                ('targetid', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TargetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=300)),
                ('target_recognition_image', models.CharField(max_length=1300)),
                ('target_text', models.CharField(max_length=400)),
                ('target_image', models.CharField(max_length=1300)),
                ('target_3d_model', models.CharField(max_length=50)),
                ('NameTH', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TreasureHuntData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('THName', models.CharField(max_length=150)),
            ],
        ),
    ]
